# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s = "Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
import numpy as np
array=np.ones(10)*5
print (array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
array=np.arange(20,36,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
import numpy as np
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
import pandas as pd
data = {'Name':['Renault', 'Duster', 'Maruti'], 'Ratings':[9.0, 8.0, 5.0]} 
df = pd.DataFrame(data, index =['position1', 'position2', 'position3'])
print(df)

              Name  Ratings
position1  Renault      9.0
position2   Duster      8.0
position3   Maruti      5.0


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
import pandas as pd
  
per1 = pd.date_range(start ='1-jan-2023', 
         end ='10-feb-2023', freq ='5H')
  
for val in per1:
    print(val)

2023-01-01 00:00:00
2023-01-01 05:00:00
2023-01-01 10:00:00
2023-01-01 15:00:00
2023-01-01 20:00:00
2023-01-02 01:00:00
2023-01-02 06:00:00
2023-01-02 11:00:00
2023-01-02 16:00:00
2023-01-02 21:00:00
2023-01-03 02:00:00
2023-01-03 07:00:00
2023-01-03 12:00:00
2023-01-03 17:00:00
2023-01-03 22:00:00
2023-01-04 03:00:00
2023-01-04 08:00:00
2023-01-04 13:00:00
2023-01-04 18:00:00
2023-01-04 23:00:00
2023-01-05 04:00:00
2023-01-05 09:00:00
2023-01-05 14:00:00
2023-01-05 19:00:00
2023-01-06 00:00:00
2023-01-06 05:00:00
2023-01-06 10:00:00
2023-01-06 15:00:00
2023-01-06 20:00:00
2023-01-07 01:00:00
2023-01-07 06:00:00
2023-01-07 11:00:00
2023-01-07 16:00:00
2023-01-07 21:00:00
2023-01-08 02:00:00
2023-01-08 07:00:00
2023-01-08 12:00:00
2023-01-08 17:00:00
2023-01-08 22:00:00
2023-01-09 03:00:00
2023-01-09 08:00:00
2023-01-09 13:00:00
2023-01-09 18:00:00
2023-01-09 23:00:00
2023-01-10 04:00:00
2023-01-10 09:00:00
2023-01-10 14:00:00
2023-01-10 19:00:00
2023-01-11 00:00:00
2023-01-11 05:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(data, columns = ['sno','Name', 'Age'])
print(df )